### ISSUE TITLE
Windows Security/Defender flags as malware

### ISSUE THREAD

**Issue by PowerPCFan** [SteavenToolBox/Windows#2]
Windows Security/Windows Defender flags the command:

`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/SteavenToolBox/Windows/main/Scripts/runtime.ps1'))` 

as a severe threat. "This program is dangerous and executes commands from an attacker." 

I've looked at that runtime.ps1 file and it's definitely not malware, it just installs prerequisites for the utility. 

Not sure if something is triggering this and if it can be fixed but this could definitely interfere with the functionality of the utility if Defender is blocking it.

**Comment by SteavenGamerYT** [comment]
just for you, runtime.ps1 is now replaced by runtime.cpp, welcome c++ runtime script, slowly going away from old cmd and ps1 to c++, hopfily one day the entire toolbox becomes c++

**Comment by PowerPCFan** [comment]
> just for you, runtime.ps1 is now replaced by runtime.cpp, welcome c++ runtime script, slowly going away from old cmd and ps1 to c++, hopfily one day the entire toolbox becomes c++

that appears to have fixed it, I'll close this issue
